"""Initialiseer FNO-databaseschema

Revision ID: dde44c75a09e
Revises:
Create Date: 2026-07-15 19:46:34.953923

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dde44c75a09e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "photo",
        sa.Column("mm_id", sa.String(length=100), nullable=False),
        sa.Column("photo_number", sa.String(length=50), nullable=False),
        sa.Column("publication_status", sa.Integer(), nullable=False),
        sa.Column("synchronized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("photo", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_photo_mm_id"), ["mm_id"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_photo_photo_number"), ["photo_number"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_photo_publication_status"),
            ["publication_status"],
            unique=False,
        )

    op.create_table(
        "role",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=250), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_role_name"), ["name"], unique=True)

    op.create_table(
        "person",
        sa.Column("photo_id", sa.Integer(), nullable=False),
        sa.Column("label_number", sa.Integer(), nullable=False),
        sa.Column("x_position", sa.Float(), nullable=False),
        sa.Column("y_position", sa.Float(), nullable=False),
        sa.Column("current_name", sa.String(length=250), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["photo_id"], ["photo.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("photo_id", "label_number", name="uq_person_photo_label"),
    )
    with op.batch_alter_table("person", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_person_current_name"), ["current_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_person_label_number"), ["label_number"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_person_photo_id"), ["photo_id"], unique=False
        )

    op.create_table(
        "user",
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_is_active"), ["is_active"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_user_role_id"), ["role_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_username"), ["username"], unique=True)

    op.create_table(
        "comment",
        sa.Column("photo_id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("author_type", sa.String(length=30), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_by_user_id", sa.Integer(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_user_id", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["closed_by_user_id"], ["user.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by_user_id"], ["user.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["person_id"], ["person.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["photo_id"], ["photo.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_comment_person_id"), ["person_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_comment_photo_id"), ["photo_id"], unique=False
        )
        batch_op.create_index(
            "ix_comment_photo_status", ["photo_id", "status"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_comment_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_comment_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "history",
        sa.Column("photo_id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["person_id"], ["person.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["photo_id"], ["photo.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_history_event_type"), ["event_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_history_person_id"), ["person_id"], unique=False
        )
        batch_op.create_index(
            "ix_history_photo_created_at", ["photo_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_history_photo_id"), ["photo_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_history_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "metadata_history",
        sa.Column("photo_id", sa.Integer(), nullable=False),
        sa.Column("field_name", sa.String(length=100), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["photo_id"], ["photo.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("metadata_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_metadata_history_changed_at"), ["changed_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_metadata_history_field_name"), ["field_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_metadata_history_photo_id"), ["photo_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_metadata_history_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "name_history",
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.Column("old_name", sa.String(length=250), nullable=True),
        sa.Column("new_name", sa.String(length=250), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["person_id"], ["person.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("name_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_name_history_changed_at"), ["changed_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_name_history_person_id"), ["person_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_name_history_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "setting",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("description", sa.String(length=250), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_by_user_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"], ["user.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("setting", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_setting_key"), ["key"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_setting_updated_by_user_id"),
            ["updated_by_user_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("setting", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_setting_updated_by_user_id"))
        batch_op.drop_index(batch_op.f("ix_setting_key"))

    op.drop_table("setting")
    with op.batch_alter_table("name_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_name_history_user_id"))
        batch_op.drop_index(batch_op.f("ix_name_history_person_id"))
        batch_op.drop_index(batch_op.f("ix_name_history_changed_at"))

    op.drop_table("name_history")
    with op.batch_alter_table("metadata_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_metadata_history_user_id"))
        batch_op.drop_index(batch_op.f("ix_metadata_history_photo_id"))
        batch_op.drop_index(batch_op.f("ix_metadata_history_field_name"))
        batch_op.drop_index(batch_op.f("ix_metadata_history_changed_at"))

    op.drop_table("metadata_history")
    with op.batch_alter_table("history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_history_user_id"))
        batch_op.drop_index(batch_op.f("ix_history_photo_id"))
        batch_op.drop_index("ix_history_photo_created_at")
        batch_op.drop_index(batch_op.f("ix_history_person_id"))
        batch_op.drop_index(batch_op.f("ix_history_event_type"))

    op.drop_table("history")
    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_comment_user_id"))
        batch_op.drop_index(batch_op.f("ix_comment_status"))
        batch_op.drop_index("ix_comment_photo_status")
        batch_op.drop_index(batch_op.f("ix_comment_photo_id"))
        batch_op.drop_index(batch_op.f("ix_comment_person_id"))

    op.drop_table("comment")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_username"))
        batch_op.drop_index(batch_op.f("ix_user_role_id"))
        batch_op.drop_index(batch_op.f("ix_user_is_active"))

    op.drop_table("user")
    with op.batch_alter_table("person", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_person_photo_id"))
        batch_op.drop_index(batch_op.f("ix_person_label_number"))
        batch_op.drop_index(batch_op.f("ix_person_current_name"))

    op.drop_table("person")
    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_role_name"))

    op.drop_table("role")
    with op.batch_alter_table("photo", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_photo_publication_status"))
        batch_op.drop_index(batch_op.f("ix_photo_photo_number"))
        batch_op.drop_index(batch_op.f("ix_photo_mm_id"))

    op.drop_table("photo")
    # ### end Alembic commands ###
